{% set name = "pygments-ansi-color" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chriskuehl/pygments-ansi-color/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 72fcd1debaeaa34220b09a60cfe6e4b75c996b7f8fcc2c881a3b87c03fa7913f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments !=2.7.3
    - python >=3.6

test:
  imports:
    - pygments_ansi_color
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygments-ansi-color/
  dev_url: https://github.com/chriskuehl/pygments-ansi-color
  license: Apache-2.0
  license_file: LICENSE
  summary: ANSI color-code highlighting for Pygments

extra:
  recipe-maintainers:
    - awvwgk
